name: testBuild workflow

on:
  push:
    branch: -dev
  pull:
    branch: -dev

  workflow_dispatch:

  jobs:
    runBuild:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: hello world
        run: echo "Hello World"
        shell: bash

    goodBye:
      run-on: ubuntu-latest
      steps:
       - name: goodbye world
       run: echo "Bye world"
       shell: bash


